### ISSUE TITLE
Timeshift does not use wayland by default

### ISSUE THREAD

**Issue by farline99** [linuxmint/timeshift#147]
**Describe the bug**
XWayland applications are bad in wayland with fractional scaling, they are blurry, so timeshift should run in wayland... and IT supports it, but wasting it's power because does not use it by default. By default it also does not support themes used by user. As of now I run it with sudo -E command and everything is ok. Make some changes in timeshift-launcher to make more people happy :D

**Comment by Bryan2333** [comment]
Timeshift is maintained by the linuxmint team right now. The default desktop environment of linuxmint is Cinnanom, which is not ported to wayland yet. So I think Timeshift will not use wayland by default until Cinnanom complete its portion to wayland.

**Comment by JosephMcc** [comment]
> Timeshift is maintained by the linuxmint team right now. The default desktop environment of linuxmint is Cinnanom, which is not ported to wayland yet. So I think Timeshift will not use wayland by default until Cinnanom complete its portion to wayland.

To expand on this a bit, Mint ships with Cinnamon, Mate, and XFCE as it's default desktops. None of these support Wayland. All of these are also pretty popular desktop environments.

**Comment by mtwebster** [comment]
It runs ok in wayland, it just that how it gets launched currently (as root) it's losing the wayland environment, and it falls back to x11. By running sudo -E it's preserving the OP's environment when it launches (and so it runs as a wayland client).

**Comment by Bryan2333** [comment]
> It runs ok in wayland, it just that how it gets launched currently (as root) it's losing the wayland environment, and it falls back to x11. By running sudo -E it's preserving the OP's environment when it launches (and so it runs as a wayland client).

UPDATE:

I find a way to launch timeshift via `pkexec` while preserving all the user environment.

1. Copy the desktop file of `timeshift-gtk` from `/usr/share/applications` to `~/.local/share/applications`
2. change the line `Exec` to `Exec=bash -c 'pkexec env $(env) timeshift-launcher'`

Now you can launch timeshift normally, and timeshift will run as a wayland client.

---

Thanks for your answer, `sudo -E timeshift-launcher` does make Timeshift run as a wayland client. I was wondering how I could do this with `pkexec`, since sudo needs to be run in the terminal.

**Comment by mrvruj** [comment]
@Bryan2333 So that command works in the terminal for me, polkit shows up properly and it launches. However, when I put it in my .desktop file, nothing appears, not even a polkit window. I am using fish, so I even tried instead writing 'pkexec env (env) timeshift-launcher', and same result. Do you have any ideas?

edit: manually making a script file with the above command (pkexec env $(env) timeshift-launcher) and then calling that from the .desktop file works properly, but I am confused why directly running that command in the .desktop file doesn't work.

**Comment by zzahkaboom24** [comment]
@Bryan2333 Your command also works perfectly for me, or would've.
The only problem for me is that in my env, I had a line saying `LESSOPEN=||/usr/bin/lesspipe.sh %s`.
Due to the %s, using your command resulted in `/usr/bin/env: ‘%s’: No such file or directory`. I am also on Fedora 40.
I changed your command to `bash -c 'pkexec env $(env | grep -v LESSOPEN) timeshift-launcher'`, so it gets rid of that, and now it also works fine for me. Thanks for your pkexec method tho.
If someone else has my issue too, I hope my change fixes it for them too

**Comment by azizsayfiddin** [comment]
> @Bryan2333 Your command also works perfectly for me, or would've. The only problem for me is that in my env, I had a line saying `LESSOPEN=||/usr/bin/lesspipe.sh %s`. Due to the %s, using your command resulted in `/usr/bin/env: ‘%s’: No such file or directory`. I am also on Fedora 40. I changed your command to `bash -c 'pkexec env $(env | grep -v LESSOPEN) timeshift-launcher'`, so it gets rid of that, and now it also works fine for me. Thanks for your pkexec method tho. If someone else has my issue too, I hope my change fixes it for them too

Did you find a better way than using the grep or similar utility? I used this script though: `dash -c 'pkexec env $(env | rg -v -e "\-\-dmenu" -e "\-\-quit\-if\-one\-screen" -e "-c") timeshift-launcher'`

**Comment by mtwebster** [comment]
In Cinnamon 6.2 (wayland) timeshift should work unmodified, as Cinnamon now handles policykit authentication for the session.

![image](https://github.com/user-attachments/assets/f225eabf-3444-43bf-befc-bf4874dba9b0)

**Comment by ghost** [comment]
> > It runs ok in wayland, it just that how it gets launched currently (as root) it's losing the wayland environment, and it falls back to x11. By running sudo -E it's preserving the OP's environment when it launches (and so it runs as a wayland client).
> 
> UPDATE:
> 
> I find a way to launch timeshift via `pkexec` while preserving all the user environment.
> 
>     1. Copy the desktop file of `timeshift-gtk` from `/usr/share/applications` to `~/.local/share/applications`
> 
>     2. change the line `Exec` to `Exec=bash -c 'pkexec env $(env) timeshift-launcher'`
> 
> 
> Now you can launch timeshift normally, and timeshift will run as a wayland client.
> 
> Thanks for your answer, `sudo -E timeshift-launcher` does make Timeshift run as a wayland client. I was wondering how I could do this with `pkexec`, since sudo needs to be run in the terminal.

Thanks alot for the work around man. It is working.

**Comment by Jennics-SG** [comment]
I'm having a problem with the .desktop file. I can open timeshift using `pkexec env` and `sudo -E` but changing the .desktop file to use `pkexec` means i get nothing when trying to open the app with wofi

**Comment by ctretyak** [comment]
how to start it with rofi?

**Comment by azizsayfiddin** [comment]
> how to start it with rofi?

Make simple script for launching timeshift and put into the .desktop file of the app.
My script:
```
bash -c 'pkexec env $(env | grep -v -e "HYPRLAND_CMD" -e "Total" -e "System" -e "User" -e "TIMEFMT" -e "Kernel" -e "\-\-dmenu" -e "\-\-quit\-if\-one\-screen" -e "-c" -e "NIX_PROFILES") timeshift-launcher'
```
Exec line of timeshift .desktop file:
```
Exec=/home/aljustiet/.local/bin/timeshift.sh
```
