### ISSUE TITLE
Is there going to be a Ubuntu (or Debian)  repo?

### ISSUE THREAD

**Issue by doogie544** [linuxmint/timeshift#21]
The instruction for installing on the github page just say to `sudo apt install timeshift` , however if you do that on Ubuntu (and I suspect debian)  you are going to get the version developed by Tony, even with Ubuntu 22.04.  That is at least according to the repos it is still linked to Tony's github if you follow the link to the homepage.

https://packages.ubuntu.com/jammy/timeshift

Only if you search in 22.10 will you be linked to this repo.

https://packages.ubuntu.com/kinetic/timeshift

That will leave anyone who wants to stay with 22.04 for the next 2 years unable to easily use this fork.  More importantly may be that if this fork is going to see further development many will be not able to use those new (and presumably wonderful) features.  Even considering how slow Ubuntu is to add new packages to the repos it may be some time even for users of 22.10 + to get those new features.

Tony had a PPA to allow users to get the most recent version of Timshift despite what version might be hosted in the Ubuntu repos.  

Are there any plans to add such a PPA for this Timeshift fork?  (hint: I hope the answer is yes)  

P.S.  Thank you for taking up and further developing this wonderful project.

**Comment by leigh123linux** [comment]
Debian or Ubuntu will need to package it.

**Comment by matinlotfali** [comment]
@leigh123linux 
I am reopening this issue because Debian and Ubuntu's policy is to freeze package versions per each distribution release and not to update packages anymore.

For example, the timeshift package for Ubuntu 22.04 LTS is using version 21.09.1-1:
https://packages.ubuntu.com/jammy/timeshift
While the timeshift package for Ubuntu 22.10 is using the latest:
https://packages.ubuntu.com/kinetic/timeshift

Similarly, in Debian, the timeshift package for Debian 11 is using version 20.11.1 while the timeshift package for Debian 12 (Testing) is using the latest:
https://packages.debian.org/search?keywords=timeshift

So the correct way of responding to this issue for users who prefer to stick with the distribution and update to the latest version of timeshift is to provide them with some instructions to add the latest version of Debian and Ubuntu repository for only and only the timeshift package.

According to [here](https://dev-random.net/how-to-install-a-single-package-from-debian-testing-through-apt/):
For Debian, one needs to add the following line to `/etc/apt/apt.conf`:
`````
APT::Default-Release "stable";
`````
Add testing repository into `/etc/apt/sources.list`:
`````
deb http://packages.debian.org/ testing/updates main contrib non-free
`````
Then run the commands below to update the timeshift:
`````
sudo apt update
sudo apt-get install -t testing timeshift
`````

For Ubuntu, the procedure needs to be the same but instead of `stable` and `testing`, we need to use `jammy` and `kinetic`.

One risk of using the approach above is that there is a high chance that it also updates the dependencies of timeshift and it would break the system. So the new issue which used to be covered on Tony's PPA and we are now missing is that:

**Is it possible that we have the most recent version of timeshift with older versions of dependencies?**

And the answer can not be "Debian and Ubuntu need to do this for you" because they will not. It is not their policy. 
Rather, the answer should be either "yes with the plan or instructions" or "no there is no plan".

**Comment by leigh123linux** [comment]
You could build/package it yourself.

**Comment by matinlotfali** [comment]
I wish @clefebvre would respond to this because I have never seen him respond in such brief, aggression, and irrelevance on straight close-ended questions.

**Comment by leigh123linux** [comment]
@matinlotfali  I am locking the thread because of your aggression!

**Comment by clefebvre** [comment]
hi @matinlotfali,

We've no plans for a PPA right now I'm sorry. That said, this is something anyone can indeed to. If Ubuntu themselves don't keep up with upstream, then a PPA can be maintained by any Ubuntu user.
