### ISSUE TITLE
Full support for encrypted home folder

### ISSUE THREAD

**Issue by Jonassenher** [linuxmint/timeshift#288]
**Is your feature request related to a problem? Please describe.**
I needed to encrypt my home folder, so I used `ecryptfs` to do this. Now while I'm setting up Timeshift, trying to click the checkbox to include only hidden files, I get the error message saying this is not possible when the home folder is encrypted.

**Describe the solution you'd like**
I wish I was able to include only hidden files even with an encrypted home folder, since some packages may do something weird to these folder and I would want to reverse the changes to these folder in the same way as with the folder outside the home folder. I don't know why adding support for this should be a problem, since the content of the home folder is visible when I'm logged in. To store an image this way, it might be necessary to first restore the image from outside the home folder form a live environment, then restart, log in and restore a second image form my home folder, but that's fine by me.

**Describe alternatives you've considered**
The alternative I have tried out is to make a bare git repo and have a script that adds all dotfiles to it and git commits on every login, but it doesn't seem to be an ideal solution.

**Comment by clefebvre** [comment]
Timeshift is designed as a system snapshot tool, not a personal file backup solution. It's outside of the scope for Timeshift, it's something that runs as root, sometimes automated, with potentially no access to your home directory at all, and no design/knowledge of relevant home files.

To perform personal file backups, a dedicated tool is recommended. There are solutions out there but timeshift simply isn't designed for that.

**Comment by Jonassenher** [comment]
> Timeshift is designed as a system snapshot tool, not a personal file backup solution. It's outside of the scope for Timeshift, it's something that runs as root, sometimes automated, with potentially no access to your home directory at all, and no design/knowledge of relevant home files.
> 
> To perform personal file backups, a dedicated tool is recommended. There are solutions out there but timeshift simply isn't designed for that.

I urge you to read my request one more time, because some way you have clearly misinterpreted what I was asking for. You seem to think that I am asking for a backup program, I don't know where you got that from?

What I request is a feature already offered by Timeshift, which is to only include hidden files inside the home directory, but not the files outside the home directory, in the snapshot. Please note: **Only** dotfiles (= hidden files), **not** personal files. I don't know what you seem to think I wanted to back up personal files, as I clearly stated I wanted the other way around, since, as you say, Timeshift is not for personal files.

So, why am I asking for this if the feature only exists? I have already answered this, but let me repeat: "I needed to encrypt my home folder, so I used ecryptfs to do this. Now while I'm setting up Timeshift, trying to click the checkbox to include only hidden files, I get the error message saying this is not possible when the home folder is encrypted."

I.e., the problem is the feature is only available when the home folder is not encrypted, and not when it is encrypted. My request to you is to make your already existing feature available also when the home folder is encrypted, so that your program works the same way to the user when the home folder is encrypted as when it is not encrypted.

Hope this clarifies, and I'm looking forward to another reply from you answering my actual request, rather than answering something completely different that was not related to my request in any way.

**Comment by clefebvre** [comment]
Timeshift itself only has access to encrypted files when/if you decrypt them (i.e. in general, when you're logged in). This means that automated snapshots taken during the boot sequence, or by other users, or anytime you're not logged in and your home dir is encrypted, would not include these files.

When files go missing between a snapshot and the next, it would need to keep track of whether this was a removal (in which case a restore should delete them) or a failure to include them.

When it's unable to restore them it would need to keep track of whether that's an issue or whether it's impossible to restore them due to encryption.

If Timeshift was only ever ran by a single user from within his own session that could work, but it isn't. It runs on automation, at boot time, from the live medium etc.. 

Note: Hidden files are the responsibility of backup tools. They are considered user/data files, not system files. They're used mostly for user configuration and have nothing to do with the system-wide state. The only reason you might want to snapshot them with the rest of the system state is to accommodate situations where programs can't handle their own configuration after a downgrade (.mozilla comes to mind).

**Comment by clefebvre** [comment]
What I described above isn't impossible but it's really complex to implement and would potentially create very hard situations to deal with.

It's not something I'm willing to invest time into.

**Comment by DJCrashdummy** [comment]
@Jonassenher your issue with timeshift aside, use FDE - in particular dm-crypt resp. LUKS - instead of file/folder encryption. FDE is more secure (e.g. helps to avoid leaking data) and on current devices it isn't slower any more; in fact it turned out that FDE uses less RAM and is even quicker than file/folder encryption on most modern devices.

...not to mention that eCryptfs in particular is unmaintained for a decade now!
